version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/challenge
      SPRING_DATASOURCE_USERNAME: otto
      SPRING_DATASOURCE_PASSWORD: otto
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: otto
      POSTGRES_PASSWORD: otto
    ports:
      - "5432:5432"
